# Generated by Django 5.2.9 on 2026-05-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='delivery_fee',
            field=models.BooleanField(default=True),
        ),
    ]
